trigger:
- main

pool:
  name: Default   # Tu agente self-hosted

steps:
- checkout: self

# Crear zip con la app antes de desplegar
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

# Deploy al WebApp de Azure
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'SC-Conserjeria-WestEurope'
    appName: 'webappconserjeria-ddgtvegdgfyfnbgqy'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
