trigger:
  branches:
    include:
      - main

pool:
  name: Default   # si usas agente self-hosted
  # vmImage: 'ubuntu-latest'  # si tienes paralelismo habilitado

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
  displayName: 'Set Python Version'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Dependencies'

- script: |
    python manage.py migrate --noinput
  displayName: 'Run Migrations'

- script: |
    python manage.py collectstatic --noinput
  displayName: 'Collect Static Files'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Project'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1'
    appType: 'webAppLinux'
    appName: 'WebAppConserjeria'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    startUpCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 core.wsgi'
  displayName: 'Deploy to Azure Web App'
