# .github/workflows/deploy.yml
name: Deploy Django to Azure App Service

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps into .python_packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Create zip package
        run: |
          zip -r app.zip . \
            -x "*.git*" \
            -x "**/__pycache__/**" \
            -x "**/.pytest_cache/**" \
            -x "**/.venv/**" \
            -x "**/venv/**" \
            -x "**/antenv/**" \
            -x "**/__oryx_packages__/**"

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: webappconserjeria02
          package: app.zip
